### ISSUE TITLE
Автодополнение

### ISSUE THREAD

**Issue by Bournwog** [bezumkin/mSearch2#34]
http://docs.modx.pro/components/msearch2/snippets/msearchform

'autocomplete' => !empty($autocomplete) ? $autocomplete : 'results',

«0» - выключить автодополнение.

Мне кажется указывая 0 - автодополнение будет работать все еще

**Comment by bezumkin** [comment]
Сниппет mSearchForm и нужен **только** для автодополнения.

В противном случае, проще использовать обычную html форму.
