### ISSUE TITLE
Некорректная фильтрация по цене ms2filter

### ISSUE THREAD

**Issue by Ibochkarev** [bezumkin/mSearch2#36]
Добрый день!

На своем рабочем сайте нашел "баг" в фильтре ms2filter. 
http://ainmoservices.es/directory/

При выборе цены товара в фильтре, например 100000 евро выводятся все объекты от 0 до 100000.

Зашел на демо сайт minishop2, повторил такие же действия - результат тот же. 

http://minishop2.com/catalog/?ms|price=3999,0

При выборе цены от 3999, не выбирая максимальную цену выводятся все товары со стоимостью от 0 до 3999.

Просьба исправить. Заранее спасибо!

**Comment by yujj** [comment]
Вы перепутали местами параметры:
http://minishop2.com/catalog/?ms|price= **3999,0**
а надо
http://minishop2.com/catalog/?ms|price= **0,3999**

всё работает отлично.

**Comment by Ibochkarev** [comment]
Спасибо! Еще в мае разобрался!
