### ISSUE TITLE
Load JavaScript at the bottom of the page

### ISSUE THREAD

**Issue by adamwintle** [bezumkin/mSearch2#37]
It's considered best practice to load JavaScript files at the bottom of the page because they block page loading (unless loaded `async`). 

The mSearch2 JavaScript is required in the `<head>` section, otherwise this error occurs `Uncaught ReferenceError: mse2FormConfig is not defined`.

It would be best to allow the JavaScript to load at the bottom of the page.

**Comment by bezumkin** [comment]
Because **config** must be at the start of the page. It can`t block page loading - it is raw text in page content, not a link to file.

Main javascript file (default.js) load at the end of body.

**Comment by adamwintle** [comment]
If I load this file: https://github.com/bezumkin/mSearch2/blob/master/assets/components/msearch2/js/web/default.js in the footer then the page has `Uncaught ReferenceError: mse2FormConfig is not defined` error, only when this file is in the `<head>` the are no JavaScript errors.

**Comment by adamwintle** [comment]
I have a custom search JavaScript, e.g. `http://cdn.domain.co.uk/assets/js/cache/search_99e2a91642.js`, could this be the issue?

In the `mse2Config` I see `"jsUrl":"\/assets\/components\/msearch2\/js\/web\/"`, do I need to make this match `/assets/js/cache/search_99e2a91642.js`?

**Comment by bezumkin** [comment]
Why you load file youself? It is registered automaticly, by default, according to [system setting mse2_frontend_js](https://github.com/bezumkin/mSearch2/blob/master/core/components/msearch2/model/msearch2/msearch2.class.php#L169-L171)

See source code of http://minishop2.com/catalog/ - everything works fine.

**Comment by bezumkin** [comment]
It seems that you are trying to add the default.js to all pages of your website. But config registered by snippet mFilter2 that is invoked not on all pages of the website.

Here the problem is - the script is exists but no config. Do not try to register default.js yourself, leave it to component.

**Comment by adamwintle** [comment]
okay, that sounds like the best solution.

Is it possible to load the default.js onto a CDN domain?

**Comment by bezumkin** [comment]
I think so. Try to specify full link to file in the system setting.

**Comment by adamwintle** [comment]
Now I let the component register the JS in the footer, but the page shows this error again: `Uncaught ReferenceError: mse2FormConfig is not defined`, which relate to this line in the JS: `var config = mse2FormConfig[form.data('key')];`

**Comment by bezumkin** [comment]
Now I think that you display search form with special class without calling of snippet **mSearchForm**.

And it [triggers this lines of script](https://github.com/bezumkin/mSearch2/blob/master/assets/components/msearch2/js/web/default.js#L648-L650).

You need to show form through calling mSearchForm or remove class `msearch2 ` from your html form.

**Comment by adamwintle** [comment]
okay, after removing the `msearch2` class from the form there is no error.

Can the default.js be minified and concatenated (using MinifyX) into all other JS files?

**Comment by bezumkin** [comment]
Then it will be loaded at all pages of site and you will receive error as in the first question.

But you can try to enable MinifyX system setting **minifyx_process_registered** for automatic collection of all registered scripts.

**Comment by adamwintle** [comment]
Very nice, I'd not seen `minifyx_process_registered` setting before. Everything is working with the JavsScript in the bottom of the page. Thank you for your help!

**Comment by bezumkin** [comment]
You are welcome!
