### ISSUE TITLE
Output in &showLog=`1` weight analysis

### ISSUE THREAD

**Issue by adamwintle** [bezumkin/mSearch2#39]
When using ```&showLog=`1` ``` it would be very useful to see the analysis of each field and TVs weight applied to the [[+weight]] total. 

For example, with `mse2_index_fields` of `tv_country:150,tv_keywords:100,pagetitle:50,longtitle:10,description:5,introtext:5,alias:5,content:1` and results like:

![screenshot 2015-09-09 17 31 06](https://cloud.githubusercontent.com/assets/167075/9759626/95920ea0-5718-11e5-9805-461cbb649dea.png)

It is hard to see quickly why these items `(4)` and `(5)` have same `weight` total of 161, and what contributes to their totals. 

### Suggested Solution
Maybe show this info in the log, or maybe output this into the `[[+weight]]` placeholder, something like this:

`Weight Total: 161. Weight Analysis:  tv_country: 0, tv_keywords: 100, pagetitle: 50, longtitle: 0, description: 5, introtext: 5, alias:0 , content: 1`

**Comment by bezumkin** [comment]
[![](https://file.modx.pro/files/6/a/7/6a7664454ff4dde964bac4a0d0b66a2cs.jpg)](https://file.modx.pro/files/6/a/7/6a7664454ff4dde964bac4a0d0b66a2c.png)

**Comment by adamwintle** [comment]
:+1: You are fast :)
